use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let std_host_dir = Path::new("../../std/host");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("std_host_embedded.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");
    code.push_str("pub fn load_std_init() -> &'static str {\n");

    // Embed _init.js
    let init_path = std_host_dir.join("_init.js");
    if init_path.exists() {
        let abs = fs::canonicalize(&init_path).unwrap();
        code.push_str(&format!(
            "    include_str!(r\"{}\")\n",
            abs.display()
        ));
    } else {
        code.push_str("    \"\"\n");
    }
    code.push_str("}\n\n");

    // Scan all .js files (except _init.js), embed them into a function
    code.push_str("pub fn load_std_host_sources() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");

    if std_host_dir.exists() {
        let mut entries: Vec<_> = fs::read_dir(std_host_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name().to_string_lossy().to_string();
                name.ends_with(".js") && name != "_init.js"
            })
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in &entries {
            let abs = fs::canonicalize(entry.path()).unwrap();
            let name = entry
                .file_name()
                .to_string_lossy()
                .trim_end_matches(".js")
                .to_string();
            code.push_str(&format!(
                "        (\"{}\", include_str!(r\"{}\")),\n",
                name,
                abs.display()
            ));
        }
    }

    code.push_str("    ]\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();

    // Re-run if std files change
    println!("cargo:rerun-if-changed=../../std/host");
}
