use std::collections::HashMap;
use vivi_sema::resolve::ResolvedProgram;

// Include the build.rs generated file
include!(concat!(env!("OUT_DIR"), "/std_host_embedded.rs"));

/// Extract named functions from a JS source string.
fn parse_js_functions(source: &str, map: &mut HashMap<String, String>) {
    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if let Some(rest) = line.strip_prefix("function ") {
            if let Some(paren_pos) = rest.find('(') {
                let name = rest[..paren_pos].trim().to_string();
                let mut depth = 0i32;
                let mut body = String::new();
                for j in i..lines.len() {
                    for ch in lines[j].chars() {
                        if ch == '{' { depth += 1; }
                        if ch == '}' { depth -= 1; }
                    }
                    body.push_str(lines[j]);
                    body.push('\n');
                    if depth == 0 {
                        i = j + 1;
                        break;
                    }
                }
                map.insert(name, body.trim().to_string());
                continue;
            }
        }
        i += 1;
    }
}

/// Build function name → JS implementation map from all std/host/*.js files.
fn build_std_fn_map() -> HashMap<String, String> {
    let mut map = HashMap::new();
    for (_module, source) in load_std_host_sources() {
        parse_js_functions(source, &mut map);
    }
    map
}

pub struct WebBuildConfig {
    pub title: String,
    pub canvas_width: u32,
    pub canvas_height: u32,
    pub wasm_filename: String,
}

impl Default for WebBuildConfig {
    fn default() -> Self {
        Self {
            title: "Vivi App".to_string(),
            canvas_width: 800,
            canvas_height: 600,
            wasm_filename: "app.wasm".to_string(),
        }
    }
}

/// Generate runtime.js content from extern fn declarations + std library.
pub fn generate_runtime_js(resolved: &ResolvedProgram, config: &WebBuildConfig) -> String {
    let std_fns = build_std_fn_map();

    let mut modules: std::collections::BTreeMap<String, Vec<&vivi_sema::resolve::ExternFnInfo>> =
        std::collections::BTreeMap::new();
    for efn in &resolved.extern_fns {
        modules.entry(efn.module_name.clone()).or_default().push(efn);
    }

    let mut js = String::new();

    // Header
    js.push_str(&format!(
        "// Auto-generated by Vivi compiler (--target web)\n\
         // Do not edit manually.\n\
         const CANVAS_WIDTH = {};\n\
         const CANVAS_HEIGHT = {};\n\
         const WASM_FILE = '{}';\n\n",
        config.canvas_width, config.canvas_height, config.wasm_filename
    ));

    // Std init
    js.push_str(load_std_init());
    js.push_str("\n\n");

    // Emit only the std functions actually used by extern declarations
    let mut emitted: std::collections::HashSet<String> = std::collections::HashSet::new();
    for fns in modules.values() {
        for efn in fns {
            if let Some(impl_str) = std_fns.get(&efn.name) {
                if emitted.insert(efn.name.clone()) {
                    js.push_str(impl_str);
                    js.push_str("\n\n");
                }
            }
        }
    }

    // Import objects
    js.push_str("const imports = {\n");
    for (module_name, fns) in &modules {
        js.push_str(&format!("  '{}': {{\n", module_name));
        for efn in fns {
            if std_fns.contains_key(&efn.name) {
                js.push_str(&format!("    '{}': {},\n", efn.name, efn.name));
            } else {
                let params: Vec<String> = efn
                    .params
                    .iter()
                    .enumerate()
                    .map(|(i, _)| format!("a{i}"))
                    .collect();
                js.push_str(&format!(
                    "    '{}': ({}) => {{ console.warn('[vivi] unimplemented extern: {}'); }},\n",
                    efn.name,
                    params.join(", "),
                    efn.name
                ));
            }
        }
        js.push_str("  },\n");
    }
    js.push_str("};\n\n");

    js.push_str(
        r#"async function boot() {
    const { instance } = await WebAssembly.instantiateStreaming(fetch(WASM_FILE), imports);
    const { init, tick, memory } = instance.exports;

    init();

    function frame() {
        tick();
        requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);
}

boot().catch(e => {
    document.body.innerHTML += `<pre style="color:red;padding:1rem">${e}\n${e.stack}</pre>`;
});
"#,
    );

    js
}

/// Generate index.html content.
pub fn generate_index_html(config: &WebBuildConfig) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
        background: #0a0a1a;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        font-family: monospace;
        color: #e0e0e0;
    }}
    h1 {{ color: #818cf8; margin-bottom: 1rem; font-size: 1.2rem; }}
    canvas {{ border: 1px solid #333; }}
    .footer {{ margin-top: 0.5rem; font-size: 0.75rem; color: #555; }}
</style>
</head>
<body>
<h1>{title}</h1>
<canvas id="vivi-canvas"></canvas>
<div class="footer">Powered by Vivi</div>
<script src="runtime.js"></script>
</body>
</html>"#,
        title = config.title
    )
}
