use vivi_sema::resolve::{ExternFnInfo, ResolvedProgram};

/// Standard host API functions that --target web auto-implements.
/// Any extern host fn matching these names gets a built-in JS implementation.
const STANDARD_HOST_API: &[(&str, &str)] = &[
    // Canvas rendering
    ("clear_screen", "() => { ctx.fillStyle = '#0a0a1a'; ctx.fillRect(0, 0, canvas.width, canvas.height); }"),
    ("set_color", "(r, g, b) => { currentColor = `rgb(${r},${g},${b})`; }"),
    ("draw_rect", "(x, y, w, h) => { ctx.fillStyle = currentColor; ctx.fillRect(x, y, w, h); }"),
    ("draw_circle", "(x, y, r) => { ctx.fillStyle = currentColor; ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fill(); }"),
    // Debug
    ("log_i32", "(v) => { console.log('[vivi]', v); }"),
    ("log_f32", "(v) => { console.log('[vivi]', v); }"),
    // Input
    ("get_mouse_x", "() => mouseX"),
    ("get_mouse_y", "() => mouseY"),
    // Time
    ("get_time", "() => performance.now()"),
];

pub struct WebBuildConfig {
    pub title: String,
    pub canvas_width: u32,
    pub canvas_height: u32,
    pub wasm_filename: String,
}

impl Default for WebBuildConfig {
    fn default() -> Self {
        Self {
            title: "Vivi App".to_string(),
            canvas_width: 800,
            canvas_height: 600,
            wasm_filename: "app.wasm".to_string(),
        }
    }
}

/// Generate runtime.js content from extern fn declarations.
pub fn generate_runtime_js(resolved: &ResolvedProgram, config: &WebBuildConfig) -> String {
    // Collect all extern modules and their functions
    let mut modules: std::collections::HashMap<String, Vec<&ExternFnInfo>> =
        std::collections::HashMap::new();
    for efn in &resolved.extern_fns {
        modules
            .entry(efn.module_name.clone())
            .or_default()
            .push(efn);
    }

    let std_api: std::collections::HashMap<&str, &str> =
        STANDARD_HOST_API.iter().copied().collect();

    let mut js = String::new();

    // Header
    js.push_str(&format!(
        r#"// Auto-generated by Vivi compiler (--target web)
// Do not edit manually.
const CANVAS_WIDTH = {};
const CANVAS_HEIGHT = {};
const WASM_FILE = '{}';

const canvas = document.getElementById('vivi-canvas');
canvas.width = CANVAS_WIDTH;
canvas.height = CANVAS_HEIGHT;
const ctx = canvas.getContext('2d');

let currentColor = '#ffffff';
let mouseX = 0;
let mouseY = 0;

canvas.addEventListener('mousemove', (e) => {{
    const rect = canvas.getBoundingClientRect();
    mouseX = e.clientX - rect.left;
    mouseY = e.clientY - rect.top;
}});

"#,
        config.canvas_width, config.canvas_height, config.wasm_filename
    ));

    // Generate import objects
    js.push_str("const imports = {\n");
    for (module_name, fns) in &modules {
        js.push_str(&format!("  '{}': {{\n", module_name));
        for efn in fns {
            if let Some(impl_str) = std_api.get(efn.name.as_str()) {
                js.push_str(&format!("    '{}': {},\n", efn.name, impl_str));
            } else {
                // Unknown extern fn — generate a no-op with warning
                let params: Vec<String> = efn
                    .params
                    .iter()
                    .enumerate()
                    .map(|(i, _)| format!("a{i}"))
                    .collect();
                let param_str = params.join(", ");
                js.push_str(&format!(
                    "    '{}': ({}) => {{ console.warn('unimplemented extern: {}'); }},\n",
                    efn.name, param_str, efn.name
                ));
            }
        }
        js.push_str("  },\n");
    }
    js.push_str("};\n\n");

    // Boot logic
    js.push_str(
        r#"async function boot() {
    const resp = await fetch(WASM_FILE);
    const bytes = await resp.arrayBuffer();
    const { instance } = await WebAssembly.instantiate(bytes, imports);
    const { init, tick, memory } = instance.exports;

    init();

    function frame() {
        tick();
        requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);
}

boot().catch(e => {
    document.body.innerHTML += `<pre style="color:red;padding:1rem">${e}\n${e.stack}</pre>`;
});
"#,
    );

    js
}

/// Generate index.html content.
pub fn generate_index_html(config: &WebBuildConfig) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
        background: #0a0a1a;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        font-family: monospace;
        color: #e0e0e0;
    }}
    h1 {{ color: #818cf8; margin-bottom: 1rem; font-size: 1.2rem; }}
    canvas {{ border: 1px solid #333; }}
    .footer {{ margin-top: 0.5rem; font-size: 0.75rem; color: #555; }}
</style>
</head>
<body>
<h1>{title}</h1>
<canvas id="vivi-canvas"></canvas>
<div class="footer">Powered by Vivi</div>
<script src="runtime.js"></script>
</body>
</html>"#,
        title = config.title
    )
}
