use std::collections::HashMap;
use vivi_sema::resolve::ResolvedProgram;

// Include the build.rs generated file
include!(concat!(env!("OUT_DIR"), "/std_host_embedded.rs"));

/// Extract named functions from a JS source string.
fn parse_js_functions(source: &str, map: &mut HashMap<String, String>) {
    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if let Some(rest) = line.strip_prefix("function ") {
            if let Some(paren_pos) = rest.find('(') {
                let name = rest[..paren_pos].trim().to_string();
                let mut depth = 0i32;
                let mut body = String::new();
                for j in i..lines.len() {
                    for ch in lines[j].chars() {
                        if ch == '{' { depth += 1; }
                        if ch == '}' { depth -= 1; }
                    }
                    body.push_str(lines[j]);
                    body.push('\n');
                    if depth == 0 {
                        i = j + 1;
                        break;
                    }
                }
                map.insert(name, body.trim().to_string());
                continue;
            }
        }
        i += 1;
    }
}

/// Build function name → JS implementation map from all std/host/*.js files.
fn build_std_fn_map() -> HashMap<String, String> {
    let mut map = HashMap::new();
    for (_module, source) in load_std_host_sources() {
        parse_js_functions(source, &mut map);
    }
    map
}

pub struct WebBuildConfig {
    pub title: String,
    pub canvas_width: u32,
    pub canvas_height: u32,
    pub wasm_filename: String,
}

impl Default for WebBuildConfig {
    fn default() -> Self {
        Self {
            title: "Vivi App".to_string(),
            canvas_width: 800,
            canvas_height: 600,
            wasm_filename: "app.wasm".to_string(),
        }
    }
}

/// Generate runtime.js content from extern fn declarations + std library.
pub fn generate_runtime_js(
    resolved: &ResolvedProgram,
    config: &WebBuildConfig,
    used_std_modules: &[String],
) -> String {
    let std_fns = build_std_fn_map();

    let mut modules: std::collections::BTreeMap<String, Vec<&vivi_sema::resolve::ExternFnInfo>> =
        std::collections::BTreeMap::new();
    for efn in &resolved.extern_fns {
        modules.entry(efn.module_name.clone()).or_default().push(efn);
    }

    let mut js = String::new();

    // Header
    js.push_str(&format!(
        "// Auto-generated by Vivi compiler (--target web)\n\
         // Do not edit manually.\n\
         const CANVAS_WIDTH = {};\n\
         const CANVAS_HEIGHT = {};\n\
         const WASM_FILE = '{}';\n\n",
        config.canvas_width, config.canvas_height, config.wasm_filename
    ));

    // Std init
    js.push_str(load_std_init());
    js.push_str("\n\n");

    // Emit only the std functions actually used by extern declarations
    let mut emitted: std::collections::HashSet<String> = std::collections::HashSet::new();
    for fns in modules.values() {
        for efn in fns {
            if let Some(impl_str) = std_fns.get(&efn.name) {
                if emitted.insert(efn.name.clone()) {
                    js.push_str(impl_str);
                    js.push_str("\n\n");
                }
            }
        }
    }

    // Import objects
    js.push_str("const imports = {\n");
    for (module_name, fns) in &modules {
        js.push_str(&format!("  '{}': {{\n", module_name));
        for efn in fns {
            if std_fns.contains_key(&efn.name) {
                js.push_str(&format!("    '{}': {},\n", efn.name, efn.name));
            } else {
                let params: Vec<String> = efn
                    .params
                    .iter()
                    .enumerate()
                    .map(|(i, _)| format!("a{i}"))
                    .collect();
                js.push_str(&format!(
                    "    '{}': ({}) => {{ console.warn('[vivi] unimplemented extern: {}'); }},\n",
                    efn.name,
                    params.join(", "),
                    efn.name
                ));
            }
        }
        js.push_str("  },\n");
    }
    js.push_str("};\n\n");

    // Include paired JS drivers for used std modules
    let uses_render = used_std_modules.iter().any(|m| m == "std.render");

    if uses_render {
        // Pass __heap_base to render driver
        let heap_base = resolved.globals.iter()
            .find(|g| g.name == "__heap_base")
            .map(|g| g.offset)
            .unwrap_or(0);
        js.push_str(&format!("const __HEAP_BASE_OFFSET = {};\n\n", heap_base));

        // Include render driver from std/host/render.js
        for (_module, source) in load_std_host_sources() {
            if _module == "render" {
                js.push_str(source);
                js.push_str("\n\n");
            }
        }
    }

    let uses_input = used_std_modules.iter().any(|m| m == "std.input");

    if uses_input {
        let input_base = resolved.globals.iter()
            .find(|g| g.name == "__input_base")
            .map(|g| g.offset)
            .unwrap_or(0);
        js.push_str(&format!("const __INPUT_BUF_OFFSET = {};\n\n", input_base));

        for (_module, source) in load_std_host_sources() {
            if _module == "input" {
                js.push_str(source);
                js.push_str("\n\n");
            }
        }
    }

    // Boot
    js.push_str(
        r#"async function boot() {
    const { instance } = await WebAssembly.instantiateStreaming(fetch(WASM_FILE), imports);
    const { init, tick, memory } = instance.exports;

    init();

    let lastTime = performance.now();
    let frameCount = 0;
    const hud = document.getElementById('vivi-hud');

    function frame() {
"#,
    );

    if uses_input {
        js.push_str("        __vivi_sync_input(memory);\n");
    }

    js.push_str("        tick();\n");

    if uses_render {
        js.push_str("        __vivi_flush_draws(memory);\n");
    }

    js.push_str(
        r#"        frameCount++;
        const now = performance.now();
        if (now - lastTime > 500) {
            const fps = (frameCount / (now - lastTime) * 1000).toFixed(0);
            let info = fps + ' FPS';
            // Read visible count from memory at address 899996 (if available)
            try {
                const view = new DataView(memory.buffer);
                const vc = view.getInt32(899996, true);
                if (vc > 0) info += ' | ' + vc.toLocaleString() + ' visible';
            } catch(e) {}
            if (hud) hud.textContent = info;
            frameCount = 0;
            lastTime = now;
        }
        requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);
}

boot().catch(e => {
    document.body.innerHTML += `<pre style="color:red;padding:1rem">${e}\n${e.stack}</pre>`;
});
"#,
    );

    js
}

/// Generate index.html content.
pub fn generate_index_html(config: &WebBuildConfig) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
        background: #0a0a1a;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        font-family: monospace;
        color: #e0e0e0;
    }}
    h1 {{ color: #818cf8; margin-bottom: 1rem; font-size: 1.2rem; }}
    .canvas-wrap {{ position: relative; display: inline-block; }}
    canvas {{ border: 1px solid #333; display: block; }}
    #vivi-hud {{ position: absolute; top: 8px; left: 10px; font-size: 0.8rem; color: #4ade80; text-shadow: 0 0 4px #000; }}
    .footer {{ margin-top: 0.5rem; font-size: 0.75rem; color: #555; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="canvas-wrap">
<canvas id="vivi-canvas"></canvas>
<div id="vivi-hud"></div>
</div>
<div class="footer">Powered by Vivi</div>
<script src="runtime.js"></script>
</body>
</html>"#,
        title = config.title
    )
}
